
services:
  queuemate-bot:
    build: .
    volumes:
      - queuemate_bot_data:/app/data  # Используем именованный том для базы данных и логов
    env_file:
      - .env
    restart: unless-stopped

volumes:
  queuemate_bot_data: # Объявляем именованный том
